config/routes.rb
Rails.application.routes.draw do
  resources :videos do
    resources :comments
    end
  devise_for :users
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :comments
        has_many :videos

end

app/models/video.rb
class Video < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_one_attached :clip
    has_one_attached :thumbnail
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_out_path_for scope
        user_session_path
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_video
    def create
       @comment = @video.comments.build(comment_params)
       @comment.user_id = current_user.id
       @comment.save
    end

    private

    def set_video
    @video = Video.find(params[:video_id])        
    end
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

    def index
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all

  end

  # GET /videos/1 or /videos/1.json
  def show
    @comment = Comment.new
    @comments = @video.comments
    @video.views = @video.views + 1
    @video.save 
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = current_user.videos.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:titile, :description, :clip, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/_comment.html.erb
<div class="comment-content">
<p><%= comment.content%></p>
</div>

app/views/comments/_form.html.erb
<div class="comment-box">
<%= form_for([@video, @comment], remote: true) do |f| %>
<%= f.label :content %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

</div>

app/views/comments/create.js.erb
var comments = document.getElementById("comments")
var commentField = document.getElementById("comment_reply")
comments.insertAdjacentHTML("beforeend", "<%= escape_javascript(render (@comment))%>")
commentField.value = ""

app/views/home/index.html.erb
<div class="flex flex-row min-h-screen bg-gray-100 text-gray-800">
 <%= render 'shared/sidebar' %>
  
    <main class="main flex flex-col flex-grow -ml-64 md:ml-0 transition-all duration-150 ease-in">
        <%= render 'shared/header' %>
      <div class="main-content flex flex-col flex-grow p-4">
        <h1 class="font-bold text-2xl text-gray-700">Dashboard</h1>
        <div
          class="flex flex-col flex-grow  rounded mt-4"
        >
        <div class="container mx-auto">
            <div class="grid grid-cols-12 gap-4">
                <div class="col-span-3">
                <div class="bg-white w-full h-24 p-4 ">
                <h4 class="font-bold text-xs text-gray-700">Recent followers</h4>
                <h4 class="font-bold text-xs text-gray-400">Today</h4>
                </div>
                </div>
                <div class="col-span-4">hello</div>
                <div class="col-span-5">hello</div>

                </div>
        </div></div>
      </div>
        <%= render 'shared/footer' %>
     
    </main>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudioApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
 <footer class="footer px-4 py-6">
        <div class="footer-content">
          <p class="text-sm text-gray-600 text-center">© Brandname 2020. All rights reserved. <a href="https://twitter.com/iaminos">by iAmine</a></p>
        </div>
      </footer>

app/views/shared/_header.html.erb
      <header class="header bg-white shadow py-4 px-4">
        <div class="header-content flex items-center flex-row">
          <form action="#">
            <div class="hidden md:flex relative">
              <div
                class="inline-flex items-center justify-center absolute left-0 top-0 h-full w-10 text-gray-400"
              >
                <svg
                  class="h-6 w-6"
                  fill="none"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </div>

              <input
                id="search"
                type="text"
                name="search"
                class="text-sm sm:text-base placeholder-gray-500 pl-10 pr-4 rounded-lg border border-gray-300 w-full h-10 focus:outline-none focus:border-indigo-400"
                placeholder="Search..."
              />
            </div>
            <div class="flex md:hidden">
              <a href="#" class="flex items-center justify-center h-10 w-10 border-transparent">
                <svg
                  class="h-6 w-6 text-gray-500"
                  fill="none"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </a>
            </div>
          </form>
          <div class="flex ml-auto">
            <a href class="flex flex-row items-center">
              <img
                src="https://pbs.twimg.com/profile_images/378800000298815220/b567757616f720812125bfbac395ff54_normal.png"
                alt
                class="h-10 w-10 bg-gray-200 border rounded-full"
              />
              <span class="flex flex-col ml-2">
                <span class="truncate w-20 font-semibold tracking-wide leading-none">John Doe</span>
                <span class="truncate w-20 text-gray-500 text-xs leading-none mt-1">Manager</span>
              </span>
            </a>
          </div>
        </div>
      </header>

app/views/videos/_form.html.erb
<%= form_with(model: video, class: "contents") do |form| %>
<% if video.errors.any? %>
<div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
   <h2><%= pluralize(video.errors.count, "error") %> prohibited this company from being saved:</h2>
   <ul>
      <% video.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
   </ul>
</div>
<% end %>
<div class="grid grid-cols-12 gap-8">
   <div class="col-span-12">
      <div class="mb-4">
         <%= form.label :titile, class:'hd-sm mb-2 block leading-none'  do %>
         title<span> <i class="fa-solid fa-circle-exclamation text-black text-xs"></i>
         <% end %>
         <%= form.text_field :titile, class: "form-field" %>
      </div>
         <div class="mb-4">
         <%= form.label :clip, class: "hd-sm mb-2 block leading-none" do %>
         Clip <span> <i class="fa-solid fa-circle-exclamation text-black text-xs"></i>
         <% end %>
         <%= form.file_field :clip, class: "form-field" %>
      </div>
         <div class="mb-4">
         <%= form.label :thumbnail, class: "hd-sm mb-2 block leading-none" do %>
         thumbnail <span> <i class="fa-solid fa-circle-exclamation text-black text-xs"></i>
         <% end %>
         <%= form.file_field :thumbnail, class: "form-field" %>
      </div>
      <div class="mb-4">
         <%= form.label :description, class: "hd-sm mb-2 block leading-none" do %>
         description <span> <i class="fa-solid fa-circle-exclamation text-black text-xs"></i>
         <% end %>
         <%= form.text_field :description, class: "form-field" %>
      </div>
   </div>
</div>
<div class="grid grid-cols-12">
   <div class="flex">
      <%= form.submit  class: "text-base border border-purple-200 rounded py-2 px-4 font-sarabun font-semibold text-white leading-none bg-purple-800 shadow-md" %>
   </div>
</div>
</div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Show this video", @video %> |
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/index.html.erb
<div class="flex flex-row min-h-screen bg-gray-100 text-gray-800">
   <%= render 'shared/sidebar' %>
   <main class="main flex flex-col flex-grow -ml-64 md:ml-0 transition-all duration-150 ease-in">
      <%= render 'shared/header' %>
      <div class="main-content flex flex-col flex-grow p-4">
         <h1 class="font-bold text-2xl text-gray-700">Videos</h1>
         <%= link_to "New video", new_video_path %>
          <div  class="grid grid-cols-12 gap-4">
                   <div class="col-span-8">
                    <h5 class="mb-2 text-xs font-bold tracking-tight text-gray-900 dark:text-white">Video</h5>
                   </div> 
                    <div class="col-span-2">
                    <h5 class="mb-2 text-xs font-bold tracking-tight text-gray-900 dark:text-white">views</h5>
                   </div> 
                    <div class="col-span-2">
                    <h5 class="mb-2 text-xs font-bold tracking-tight text-gray-900 dark:text-white">comments</h5>
                   </div> 
                  </div>
         <div
            class="bg-white"
            >
            <div class="container mx-auto">
                  <p style="color: green"><%= notice %></p>
                 
               <div class="grid grid-cols-12 gap-4">
                  <% @videos.each do |video| %>
                  <div class="col-span-3">
                  <div class="">
                   <video id="my-video" class="video-js" controls preload="auto"   poster="<%= url_for(video.thumbnail)  %>" class="w-72" data-setup="{}">
                        <source src="<%= url_for(video.clip) %>" type="video/mp4" width="640" height="240">
                     </video>
                     </div>
                  </div>
                    <div class="col-span-5">
                     <div class="leading-normal">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">  <%= video.titile %></h5>
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= video.description %></p>
                     </div>
                    </div>
                    <div class="col-span-2">
                     <p>
                     <%= video.views %>
                  </p>
                    </div>
                     <div class="col-span-2">
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">10</p>
                    </div>
                     <%= link_to "Show this video", video %>
                      <%= time_tag video.created_at, "data-local": "time-ago"%>

                  <% end %>
               </div>
            </div>
         </div>
      </div>
      <%= render 'shared/footer' %>
   </main>
</div>

app/views/videos/new.html.erb
<div class="flex flex-row min-h-screen bg-gray-100 text-gray-800">
 <%= render 'shared/sidebar' %>
    <main class="main flex flex-col flex-grow -ml-64 md:ml-0 transition-all duration-150 ease-in">
        <%= render 'shared/header' %>
      <div class="main-content flex flex-col flex-grow p-4">
        <h1 class="font-bold text-2xl text-gray-700">New Videos</h1>
       <%= render "form", video: @video %>
        <div>
          <%= link_to "Back to videos", videos_path %>
        </div>
      </div>
        <%= render 'shared/footer' %>
     
    </main>
  </div>

app/views/videos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @video %>

<div>
  <%= link_to "Edit this video", edit_video_path(@video) %> |
  <%= link_to "Back to videos", videos_path %>

  <%= button_to "Destroy this video", @video, method: :delete %>
  <%= render  "comments/form" %>

<div id="comments">
   <%= render  @comments %>
</div>
</div>